
// This file is auto-generated by the Python analysis script.
const analysisData = {
    pixelsPerCm: 18.983050847457626,
    annotatedImageUrl: "C:/Users/user/Desktop/tomer/images/final_analysis.jpg"
};
